"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const circle_1 = require("./circle");
const rectangle_1 = require("./rectangle");
const shape_1 = require("./shape");
const myShape = new shape_1.Shape(10, 15);
console.log(myShape.getInfo());
const myCircle = new circle_1.Circle(5, 10, 20);
console.log(myCircle.getInfo());
const myRectangle = new rectangle_1.Rectangle(0, 0, 4, 5);
console.log(myRectangle.getInfo());
